### ISSUE TITLE
没有使用说明吗

### ISSUE THREAD

**Issue by q1998763** [jemmyzheng/fis3SmartyTool#1]
如题

**Comment by jemmyzheng** [comment]
这个只是对fis3做了一层封装，然后把fis3-smarty的配置集成进去了的，tests下就是个用例，全局安装后fst --help 就可以看到使用说明哈，
这个只是针对公司团队里面其他前端不熟悉构建工具（说实话，fis3的smarty解决方案总是会有莫名奇妙的坑，还有不是很好用）的情况下临时写的一个小工具。
